name: "Dump stuff from Azure"

on:
  workflow_dispatch:
  schedule:
    - cron:  '44 6 * * *'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  Get-AzRoles:
    runs-on: ubuntu-latest
    steps:
      ## CHECKOUT CODE
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      # Login, dump, diff, ev commit, push and merge
      - uses: ./.github/actions/dump-and-push
        with:
          branch_name: 'Automated-Role-Dump'
          save_path: 'azRoles/'
          resource_type: Roles
  
  Get-AzPolicies:
    runs-on: ubuntu-latest
    env:
      azRolesPath: 'azPolicies/'
      newBranch: 

    steps:
      ## CHECKOUT CODE
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      # Login, dump, diff, ev commit, push and merge
      - uses: ./.github/actions/dump-and-push
        with:
          branch_name: 'Automated-Policies-Dump'
          save_path: 'azPolicies/'
          resource_type: Policies
