name: "Dump stuff from Azure"

on:
  workflow_dispatch:
  schedule:
    - cron:  '44 6 * * *'

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
jobs:
  Get-AzRoles:
    runs-on: ubuntu-latest
    steps:
      ## CHECKOUT CODE
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      # Login, dump, diff, ev commit, push and merge
      - name: Dump and push - Roles
        uses: ./.github/actions/dump-and-push
        with:
          branch_name: 'Automated-Role-Dump'
          save_path: 'azRoles/'
          resource_type: Roles
          rinse_previous: yes
  
  Get-AzPolicies:
    runs-on: ubuntu-latest
    steps:
      ## CHECKOUT CODE
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      # Login, dump, diff, ev commit, push and merge
      - name: Dump and push - Policies
        uses: ./.github/actions/dump-and-push
        with:
          branch_name: 'Automated-Policies-Dump'
          save_path: 'azPolicies/'
          resource_type: Policies
          rinse_previous: yes

  Get-AzLocations:
    runs-on: ubuntu-latest
    steps:
      ## CHECKOUT CODE
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      # Login, dump, diff, ev commit, push and merge
      - name: Dump and push - Locations
        uses: ./.github/actions/dump-and-push
        with:
          branch_name: 'Automated-Locations-Dump'
          save_path: 'azLocations/'
          resource_type: Locations
          rinse_previous: yes

  Get-ProviderOperations:
    runs-on: ubuntu-latest
    steps:
      ## CHECKOUT CODE
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      # Login, dump, diff, ev commit, push and merge
      - name: Dump and push - ProviderOperations
        uses: ./.github/actions/dump-and-push
        with:
          branch_name: 'Automated-ProviderOperations-Dump'
          save_path: 'azProviderOperations/'
          resource_type: ProviderOperations
          rinse_previous: yes
